# Generated by Django 5.0.4 on 2024-06-01 06:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/found-items')),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('date_found', models.DateTimeField()),
                ('is_returned', models.BooleanField(default=False)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='api.user')),
            ],
            options={
                'verbose_name_plural': 'Found Items',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/lost-items')),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('date_lost', models.DateTimeField()),
                ('is_found', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to='api.user')),
            ],
            options={
                'verbose_name_plural': 'Lost Items',
            },
        ),
    ]
