# Generated by Django 5.0.4 on 2024-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_founditem_lostitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
