# Generated by Django 5.0.4 on 2024-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_username_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
